// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParseMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum MessageLiteType

typedef GPB_ENUM(MessageLiteType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  MessageLiteType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 心跳 */
  MessageLiteType_PingLite = 0,

  /** 消息下发 */
  MessageLiteType_PushLiteMessage = 1,
};

GPBEnumDescriptor *MessageLiteType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MessageLiteType_IsValidValue(int32_t value);

#pragma mark - ParseMessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ParseMessageRoot : GPBRootObject
@end

#pragma mark - ContentLiteMessage

typedef GPB_ENUM(ContentLiteMessage_FieldNumber) {
  ContentLiteMessage_FieldNumber_Type = 1,
  ContentLiteMessage_FieldNumber_Body = 2,
};

/**
 * *
 * 车机影像管理和手机app 交互
 **/
@interface ContentLiteMessage : GPBMessage

/** 类型 */
@property(nonatomic, readwrite) MessageLiteType type;

/** 具体业务 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *body;

@end

/**
 * Fetches the raw value of a @c ContentLiteMessage's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ContentLiteMessage_Type_RawValue(ContentLiteMessage *message);
/**
 * Sets the raw value of an @c ContentLiteMessage's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetContentLiteMessage_Type_RawValue(ContentLiteMessage *message, int32_t value);

#pragma mark - PingLiteRequest

typedef GPB_ENUM(PingLiteRequest_FieldNumber) {
  PingLiteRequest_FieldNumber_SeqId = 1,
};

@interface PingLiteRequest : GPBMessage

@property(nonatomic, readwrite) int64_t seqId;

@end

#pragma mark - PushLiteMessage

typedef GPB_ENUM(PushLiteMessage_FieldNumber) {
  PushLiteMessage_FieldNumber_Type = 1,
  PushLiteMessage_FieldNumber_Content = 2,
};

@interface PushLiteMessage : GPBMessage

/** 具体业务类型（PUSH_FILE_TO_APP为车机推送文件到手机，其他等等） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

/** 业务json字符串 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
